---
- name: MHN Client | registration
  include: registration.yml honeypot=glastopf
- set_fact:
    deploy: /root/.registration_done-glastopf

- shell: "echo {{ server_url }} | sed 's#^http://##; s#^https://##; s#/.*$##; s/:.*$//'"
  register: HPF_HOST
  changed_when: False
- set_fact:
    HPF_PORT: 10000
- shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"identifier\"]'"
  register: HPF_IDENT
  changed_when: False
- shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"secret\"]'"
  register: HPF_SECRET
  changed_when: False

- name: Ubuntu | Install glastopf dependencies
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python2.7
    - python-openssl
    - python-gevent
    - libevent-dev
    - python2.7-dev
    - build-essential
    - make
    - python-chardet
    - python-requests
    - python-sqlalchemy
    - python-lxml
    - python-beautifulsoup
    - mongodb
    - python-dev
    - python-setuptools
    - git
    - php5
    - php5-dev
    - liblapack-dev
    - gfortran
    - libmysqlclient-dev
    - libxml2-dev
    - libxslt-dev
    - supervisor
    - python-pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | Install glastopf dependencies
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - supervisor
    - python-pip
    - python-devel
    - python-gevent
    - libevent-devel
    - "@Development tools"
    - make
    - python-chardet
    - python-requests
    - python-sqlalchemy
    - python-lxml
    - python-BeautifulSoup
    - mongodb
    - php
    - php-devel
    - lapack-devel
    - gcc-gfortran
    - mariadb-devel
    - libxml2-devel
    - libxslt-devel
## FIXME! rpm missing?
#    - python-openssl
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

## Note: may conflict w release for other modules: contop, snort
- stat: path=/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg
  register: distribute
- name: download distribute python
  get_url: url=https://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz dest=/tmp/distribute-0.6.35.tar.gz mode=0440
  when: not distribute.stat.exists
- command: "tar xzf /tmp/distribute-0.6.35.tar.gz -C /tmp/"
  when: not distribute.stat.exists
- command: "python setup.py install chdir=/tmp/distribute-0.6.35"
  when: not distribute.stat.exists

- pip: name="git+https://github.com/threatstream/hpfeeds.git#egg=hpfeeds-dev"

- stat: path=/opt/BFR
  register: bfrdir
- name: git clone glastopf
  git:
    repo=https://github.com/mushorg/BFR.git
    dest=/opt/BFR
  when: not bfrdir.stat.exists
- stat: path=/opt/BFR/modules/bfr.so
  register: bfrinstall
- command: "{{ item }} chdir=/opt/BFR"
  with_items:
    - phpize
    - "./configure --enable-bfr"
    - make
    - "make install"
  when: not bfrinstall.stat.exists

- shell: "find /usr/lib/php5/ -type f -name bfr.so | awk -F'/' '{print $5}'"
  register: BFR_BUILD_OUTPUT

- lineinfile: "dest=/etc/php5/apache2/php.ini regexp='^zend_extension = /usr/lib/php5/{{ BFR_BUILD_OUTPUT.stdout }}/bfr.so' line='zend_extension = /usr/lib/php5/{{ BFR_BUILD_OUTPUT.stdout }}/bfr.so'"

- service: name=apache2 state=stopped enabled=no

- command: "pip install --upgrade greenlet"

- pip: name=glastopf

- file: path=/opt/glastopf state=directory mode=0755

- template: src=glastopf.cfg dest=/opt/glastopf/glastopf.cfg mode=0644

- name: set glastopf supervisor config
  template: "src=glastopf.conf dest={{ supervisor_confdir }}/glastopf.{{ supervisor_ext }} mode=0644"
  notify:
    - supervisor update

